services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # LOCALE
    #

    Pimcore\Localization\LocaleServiceInterface:
        public: true
        class: Pimcore\Localization\LocaleService

    # formatting service for dates, times and numbers
    Pimcore\Localization\IntlFormatter:
        public: true
